inherit_from:
  - .rubocop_new.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: "3.2"

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: braces

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
