inherit_from:
  - .rubocop_new.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: "3.2"

Naming/MethodParameterName:
  Enabled: false

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: braces

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/MethodLength:
  Max: 200

Metrics/ModuleLength:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 50
