module RbsMacros
  class Environment
    attr_reader object_class: MetaModule
    attr_reader decls: Array[DeclarationEntry]

    def initialize: () -> void

    def meta_eval_ruby: (String) -> void

    def add_decl: (RBS::AST::Declarations::t | RBS::AST::Members::t decl, mod: MetaModule, file: String) -> void

    def out_files: () -> Array[String]

    class DeclarationEntry < Data
      attr_reader declaration(): RBS::AST::Declarations::t | RBS::AST::Members::t
      attr_reader mod(): MetaModule
      attr_reader file(): String
      def self.new: (declaration: RBS::AST::Declarations::t | RBS::AST::Members::t, mod: MetaModule, file: String) -> instance
      def initialize: (declaration: RBS::AST::Declarations::t | RBS::AST::Members::t, mod: MetaModule, file: String) -> void
    end
  end
end
