module RbsMacros
  interface _FS
    def read: (String path) -> String
    def write: (String path, String content) -> void
  end
  def self.run: (macros: Array[Macro], ?loader: RBS::EnvironmentLoader?, ?fs: _FS) ?{ (Environment) -> void } -> void
end
