class RbsMacrosTest < Minitest::Test
  def test_version_number: () -> void

  class DummyFS
    include RbsMacros::_FS
    @files: Hash[String, String]
    def initialize: () -> void
  end

  class DummyMacro < RbsMacros::Macro
  end
end

