module RbsMacros
  module Macros
    class ForwardableMacros < Macro
      def meta_def_delegator: (Environment::HandlerParams params) -> void

      def method: (:meta_def_delegator) -> ^(Environment::HandlerParams params) -> void
                | ...

      private

      def widened_instance: (RBS::Types::t type, builder: RBS::DefinitionBuilder) -> [RBS::Definition, RBS::Substitution]?
    end
  end
end
